### PR TITLE
Remove from table when ezuser deleted

### PR DESCRIPTION
**Pull request by wizhippo**

### CODE REVIEW

**Comment by emodric** [comment]
Looks good to me! :+1: 

Ping @iherak @alymdrictels

**Comment by iherak** [comment]
Sorry for the late reply @wizhippo.

+1 from me. @alymdrictels your input?

**Comment by alymdrictels** [comment]
I've tested this locally, and I've found a couple gotchas which have to be considered:

Deleting user content objects in the legacy administration does not trigger the signal. I can think of a few ways of implementing this hook in the legacy, but none are particularly clean IMO and/or easily implementable to keep this package reasonably self-contained.

Using the ContentService->deleteContent on the User content does not, as one would expect, delete the associated entry in the user table (i.e. trigger this signal). This is by design (https://doc.ez.no/eZ-Publish/User-manual/5.x/The-Website-Interface/User-Guide/Managing-User-Accounts).

UserService->deleteUser works as expected.

Thoughts, @wizhippo, @iherak, @emodric ?

**Comment by emodric** [comment]
> but none are particularly clean IMO and/or easily implementable to keep this package reasonably self-contained.

Actually, it could be done fairly easy by integrating a legacy extension which is bundled in `ezpublish_legacy` folder which has a trigger that acts on removing content.

> Using the ContentService->deleteContent on the User content does not, as one would expect, delete the associated entry in the user table (i.e. trigger this signal).

Yes, `ContentService::deleteContent` does not delete from `ezuser` table and that is OK. That's why this PR adds a slot that acts on `UserService\DeleteUserSignal` signal from `UserService::deleteUser` method and not `ContentService\DeleteContentSignal`. If the bundle is using `ContentService::deleteContent` for deleting users, that is obviously wrong and needs to be fixed. Otherwise, it's a non issue.

**Comment by alymdrictels** [comment]
After some discussion, we'll leave the legacy hook as a to-do.

Support for legacy will involve the addition of 2 steps to the bundle installation procedure - activating the extension and creating the workflow (with instructions).

:+1:

**Comment by emodric** [comment]
@wizhippo Do you by any chance need a legacy trigger too at this moment?

**Comment by wizhippo** [comment]
@emodric I have no need for legacy support for this at this time.

**Comment by emodric** [comment]
Thanks @wizhippo !

**Comment by alymdrictels** [comment]
I've implemented the legacy workflow event, will hopefully add another PR tomorrow after some cleanup and updating the docs.

**Pull request merged**
